version: "3.9"
services:
  spvending-api-image:
    image: gitlab:5050/adrian-manuel/spvending-managment:${DEPLOY_TAG}
    container_name: spvending-api-production-container
    ports:
      - "8081:8080"
    networks:
      - spring-network
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6380:6379"
    networks:
      - spring-network

  postgres:
    image: postgres
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: tenants_managment
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    networks:
      - spring-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data

networks:
  spring-network:
    driver: bridge

volumes:
  postgres-volume:
