version: "3.9"
services:
  spvending-api-image-production:
    image: gitlab:5050/adrian-manuel/spvending-managment:${DEPLOY_TAG}
    container_name: spvending-api-production-container
    ports:
      - "8082:8080"
    networks:
      - spring-network-production
    depends_on:
      - postgres-production
      - redis-production

  redis-production:
    image: redis
    container_name: redis_cache_production
    ports:
      - "6381:6379"
    networks:
      - spring-network-production

  postgres-production:
    image: postgres
    container_name: postgres_database_production
    environment:
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: tenants_managment_production
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    networks:
      - spring-network-production
    volumes:
      - postgres-volume-production:/var/lib/postgresql/data

networks:
  spring-network-production:
    driver: bridge

volumes:
  postgres-volume-production:
