services:
  spvending-api-image-production:
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_TAG}
    container_name: spvending-api-production-container
    ports:
      - "8082:8080"
    networks:
      spring-network-production:
        ipv4_address: 172.28.0.10

    depends_on:
      - postgres-production
      - redis-production
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-production:5432/tenants_managment_production
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abc123.
      - SPRING_REDIS_HOST=redis-production
  redis-production:
    image: redis
    container_name: redis_cache_production
    ports:
      - "6381:6379"
    networks:
      - spring-network-production

  postgres-production:
    image: postgres
    container_name: postgres_database_production
    environment:
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: tenants_managment_production
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    networks:
      - spring-network-production
    volumes:
      - postgres-volume-production:/var/lib/postgresql/data

networks:
  spring-network-production:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
volumes:
  postgres-volume-production:
