version: "3.9"
services:
  spvending-api-image-staging:
    image: gitlab:5050/adrian-manuel/spvending-managment:${DEPLOY_TAG}
    container_name: spvending-api-staging-container
    ports:
      - "8080:8080"
    networks:
      - spring-network-staging
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - spring-network-staging

  postgres:
    image: postgres
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: tenants_managment
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-network-staging
    volumes:
      - postgres-volume:/var/lib/postgresql/data

networks:
  spring-network-staging:
    driver: bridge

volumes:
  postgres-volume:
