version: "3.9"
services:
  spvending-api-image-staging:
    image: gitlab:5050/adrian-manuel/spvending-managment:${DEPLOY_TAG}
    container_name: spvending-api-staging-container
    ports:
      - "8081:8080"
    networks:
      - spring-network-staging
    depends_on:
      - postgres-staging
      - redis-staging
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-staging:5432/tenants_managment_staging
  redis-staging:
    image: redis
    container_name: redis_cache
    ports:
      - "6380:6379"
    networks:
      - spring-network-staging

  postgres-staging:
    image: postgres
    container_name: postgres_database_staging
    environment:
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: tenants_managment_staging
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    networks:
      - spring-network-staging
    volumes:
      - postgres-volume-staging:/var/lib/postgresql/data

networks:
  spring-network-staging:
    driver: bridge

volumes:
  postgres-volume-staging:
