version: "3.9"
services:
  spvending-api-image:
    image: spvending-api-image
    container_name: spvending-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: abc123.
      POSTGRES_DB: tenants_managment
      POSTGRES_USER: postgres

    ports:
      - "5434:5432"
    networks:
      - spring-network
    volumes:
      - postgres-volume:/var/lib/postgres
networks:
  spring-network:
volumes:
  postgres-volume:


